DefaultContentLanguage = "zh" # 主题显示语言，支持：en, fr, zh, zh-hant
baseURL = "https://xlglife.github.io" # 网站的基本URL
copyright = "浙ICP备2024102625号" # 版权信息
languageCode = "zh_CN" # 语言代码
theme = "diary" # 主题名称
title = "小洛哥开源笔记" # 网站标题

[taxonomies] #定义内容分类法
category = "categories" # 目录分类
tag = "tags" # 标签分类
series = "series"

# googleAnalytics = "UA-123-45"  # Google Analytics 代码
# googleSiteVerification = "xxxx-xxxx" # Google 网站验证

[params]
enableAutoDarkMode = true # 自动启动黑暗模式
enableReadingTime = true # 阅读时间
subtitle = "Themed by Diary." # 副标题
# favicon = "Your Favicon Address"

[markup]
[markup.highlight]
codeFences = true # 启用代码框（使用 ``` 包围的代码块）
guessSyntax = false # 不猜测代码的语法
hl_Lines = "" # 要高亮显示的行，使用逗号分隔
lineNoStart = 1 # 行号的起始值
lineNos = false # 是否显示行号
lineNumbersInTable = true # 行号显示在表格中
noClasses = true # 不使用 CSS 类（使用内联样式）
style = "perldoc" # 代码高亮的样式
tabWidth = 4 # 制表符宽度

# Twitter Card 和 Open Graph 设置
description = "My HomePage Description" # 设置 'og:description'
enableOpenGraph = false # 启用Open Graph
enableTwitterCards = false # 启用Twitter Card
title = "小洛哥开源笔记" # 设置 'og:site_name'

# 自定义导航
[[menu.main]]
name = "归档"
url = "/posts"
weight = 1
[[menu.main]]
name = "目录"
url = "/categories"
weight = 2
[[menu.main]]
name = "标签"
url = "/tags"
weight = 3
[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 4
[[menu.main]]
name = "小报童精选"
url = "https://xiaobots.top"
weight = 5
[[menu.main]]
name = "系列"
url = "/series"
weight = 6

